# Generated by Django 2.2.3 on 2019-07-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('clientes', '0006_auto_20190711_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empregado',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='telefone',
            old_name='empregado',
            new_name='cliente',
        ),
    ]
